### ISSUE TITLE
Biosyntax Publication

### ISSUE THREAD

**Issue by Jwong684** [ababaian/bioSyntax#13]
Hi all,

During the Hackathon, I have been working on drafting up a report for a paper that we could put together for publication. I have drafted up a brief skeleton of what our project is about and added figures to demonstrate our tool's utility.

UPDATED MANUSCRIPT FILE. SEE COMMENT BELOW.

I'm not exactly sure how public this is, so I have set the share settings to "can comment" for now. Let me know if you want to add/modify anything in there.

Cheers,

J

**Comment by ababaian** [comment]
Nice outline @Jwong684. You need to tell us what you want us to do exactly and we can get to work on it.

**Comment by Jwong684** [comment]
Perhaps everyone can write a brief paragraph about what they did specifically for their file formats (and if there are any features in there that they want to particularly highlight). I just glossed over it in a succinct way under the "Sublime" paragraph. It's currently sitting at around 600 words; Jake wants the paper to be under 1000 words for cheaper submission purposes (Hackseq will fund the submission fees).

I think porting the formats into vim would be a bigger priority. Once we have that down, then we can probably just add in an extra line and then submit it.

This is the journal that Jake was proposing for Hackathons and a sample paper:
https://f1000research.com/articles/5-674/v1

Essentially there's an open peer review process, where three random people from the community reviews it and approves or rejects it. I also only covered other tools very quickly in the introduction, while this group in the sample paper referenced way more publications. Perhaps each person can take a look at an additional paper so our references can go up to at least 10 citations.

**Comment by Jwong684** [comment]
Jake also had these comments during the meetings:

Things to put in Google Doc: Authors with Affiliations, Suggested Reviewers, Start on your plan (bulletpoints) for Intro, Methods & Results

Intro & Methods are the most important bits (justify the project well and explain your method well). Results need to show that the method gives reasonable results, not that it is definitively the best approach to this problem

All the things I just said about your Github repo:
1. Think of a cool name (if you don't have one). Branding is actually pretty important. A cool logo can also be really beneficial too.
2. Write up a few sentences at the start to explain the problem and how your project addresses it
3. If appropriate, include a tiny bit of test data and the explicit commands (or code) to run your tool
4. If you have multiple READMEs, it may be time to think about merging them
5. Installation instructions are also very useful. Do they just need to clone your repo? What prerequisites do you need for it? Does it use a particular version of Python? Does it need R?
6. Some boiler plate language at the bottom about licensing, contributions and where to get help makes it look more rounded. For example: https://github.com/ldiary/pytest-testbook
(but also don't have whole sections with TODO)
7. Check that your repo has a license. Look for a LICENSE file and mention it in the Readme

**Comment by alyeffy** [comment]
All this sounds good. Any idea when we should complete this by?

**Comment by Jwong684** [comment]
@ababaian What do you think? Do you feel like we should try to complete as many packages as we can before we write it up?

If we can maybe port over a couple more file formats to .vim or .gedit, then it would be pretty good. Otherwise, I think we can literally just submit it as is with a couple of additions/lit searches.

If we try to perfect it with a full port, then it'd take at least a couple weeks to a couple months.

If we just port vcf, sam, and bed to vim, maybe it'd take a couple weeks? I know that the grad students would only be able to work on this on weekends probably.

Can someone make the LICENSE file? Perhaps Alyssa @alyeffy?

**Comment by ababaian** [comment]
I've added GNU 3.0 License for now. We can discuss the specifics of licenses in the future.

Thoughts we can include in the paper: 
- Include a "Limitations" section in the bioSyntax paper; which formats or types don't work well with syntax highlighting --> unformatted or 'free' fields in bed files etc...
- Make a table for the special 'Biological Classes' which we unify across all file formats for easy reading (nucleotides, amino acids, PHRED, genomic coordinates etc...)

**Comment by ababaian** [comment]
I spent a few hours this morning going over the manuscript draft and have divvied up the sections to a few independent parts.

- [x] TASK1 + 2 : @fransilvion (two parts, referencing)
- [x] TASK2: 
- [x] TASK3: @lazypanda10117 
- [x] TASK4 + 5: @Jwong684 
- [x] TASK5:
- [x] TASK6: @ababaian

@Ebedthan / @alyeffy please review the manuscript carefully for spelling /grammar changes.

**Comment by ababaian** [comment]
KK Team bioSyntax. We've written the manuscript!

Please read over the manuscript and figures, we need each of us to approve the manuscript and ensure there are no spelling or grammar mistakes. Please take 30 minutes or so and do this very carefully. Add your comments/thoughts. Make sure your name and affiliations are correct. If you have a scholarship add that to the bottom.

[Manuscript](https://docs.google.com/document/d/1KkST6TtCc4XOriY-je4YwZ4ivoU7AzLW9USmJwYe-1U/edit?usp=sharing)
[Figures](https://drive.google.com/open?id=1P3jDmw5QTkqKyRWAFXmXHxtpl1F2FkFE)

Once you're satisfied then check off your name.
- [x] Artem
- [x] Anicet @Ebedthan 
- [x] Alyssa @alyeffy 
- [x] Gherman @fransilvion 
- [x] Jeff @lazypanda10117 
- [x] Jasper @Jwong684 


Edit: We're all good! Submitting tomorrow.
