### ISSUE TITLE
File Format / Syntax Compatibility Matrix

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#14]
File format and software compatibility matrix for bioSyntax.

|   | status            |
|---|:------------------|
| X |   Syntax Complete |
| o |   In Development  |
| - |   Unavailable     |
| * |   Bug Fix Needed  |

## Core Syntaxes

| File Format | Description                 | sublime | vim | gedit | less |
|:------------|:----------------------------|:-------:|:---:|:-----:|:----:|
| .fasta      | Generic nt/aa sequence      |    X    |  X  |   X   |   X  |
| .fastq      | Fasta + PHRED quality       |    X    |  X  |   X   |   X  |
| .clustal    | Multiple Sequence Alignment |    X    |  X  |   X   |   X  |
| .bed        | Genomic Ranges              |    X    |  X  |   X   |   X  |
| .gtf        | Genomic Annotation          |    X    |  X  |   X   |   X  |
| .pdb        | Protein Structure           |    X    |  X  |   Anc |   X  |
| .vcf        | Variant Call Format         |    X    |  X  |   X  |   X  |
| .sam        | NGS Sequence Data           |    X    |  X  |   X  |   X  |

## Auxillary Syntaxes

| File Format | Description                 | sublime | vim | gedit | less |
|-------------|-----------------------------|:-------:|:---:|:-----:|:----:|
| .fasta      | fasta alternative AA colors |         |     |       |      |
| -           | Clustal                     |    X    |  o  |   X   | -    |
| -           | Taylor                      |    X    |  o  |   X   | -    |
| -           | Zappo                       |    X    |  o  |   X   | -    |
| -           | Hydrophobicity              |    X    |  o  |   X   | -    |
| .fai        | Fasta Index (faidx)         |    X    |  X  |   X   | X    |
| .flagstat   | samtools flag summary       |    X    |  -  |   -   | X    |
| .wig        | Wiggle data                 |    o    |  -  |   X   | -    |
| .newick     | Tree Format                 |    -    |  -  |   -   | -    |
| .pdbx       | Protein Structure (large)   |    -    |  -  |   -   | -    |
| .phylip     | Multiple Sequence Alignment |    -    |  -  |   -   | -    |
| .cwl        | Common Workflow Language    |    -    |  -  |   -   | -    |

**Comment by Ebedthan** [comment]
@ababaian did you check my job in the /syntax/gedit/ folder ? I think i moved forward porting syntax to gedit. Can you evaluate it, and send me an review on the works? Thanks

**Comment by alyeffy** [comment]
Might I suggest including compatibility for Atom as well?

**Comment by ababaian** [comment]
I've heard a few people mention Atom; 
1) What kind of syntax highlighting is required, which language is it written in? i.e. if it's textMarkup then the sublime files may be easily converted.

I also would like to get the core set of highly polished syntaxes done for the publication and then look at expanding compatibility.

**Comment by alyeffy** [comment]
Atom is GitHub's own open-source text editor that's cross-platform (Linux, Mac, Windows). A quick google search shows quite a few tutorials on creating your own syntax highlighting. Seems like it's also based on the one in TextMate (i.e. it should be fairly easy to convert the Sublime Text ones to be compatible with Atom).
