### ISSUE TITLE
Porting to Atom

### ISSUE THREAD

**Issue by alyeffy** [ababaian/bioSyntax#19]
By popular demand, I think it'd be a good idea to port all the syntax files to [Atom](https://atom.io/) as well. Atom is Github's open source text-editor that is cross-platform (Mac, Windows, Linux).

Its syntax highlighting system is based on [TextMate's language grammar](http://manual.macromates.com/en/language_grammars) so converting the current Sublime Text files that we have to be compatible with Atom should be fairly straightforward. The only difference is that we'll be creating .cson files (basically custom JSON-like CSS files) and a less file for the colour scheme. I would like to work on this and if anyone else would as well, let me know :)

Here's some resources I found that seem helpful:
- [TextMate language in CSON style](https://gist.github.com/DamnedScholar/622926bcd222eb1ddc483d12103fd315)
- [Create an Atom syntax-highlighting package](https://www.sitepoint.com/how-to-write-a-syntax-highlighting-package-for-atom/)
- [Creating a theme in Atom](http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/)

**Comment by ababaian** [comment]
This is your baby @alyeffy ;)

If it's labour-intense (a non-scritable operation) then we'll for sure prioritize an atom port after publication.
