### ISSUE TITLE
bioSyntax Meeting 1

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#20]
Moving forward with bioSyntax we'll meet for ~1 hour to discuss the logistics of the next month, maybe also use the opportunity to hammer out some code while we're together. I've set times for 6pm PST since we have work/school. Please also indicate if you would prefer to meet at the UBC library or in the BC Cancer Research Centre (Broadway + Cambie).

We'll Meet at Wednesday Nov 1 6pm at the Irving K Barber Library and video conference in remote people.

**Agenda:** (add things)
1) Define Release 1.0 'Finish Criteria' for bioSyntax (All)
-- File Formats
-- Software Ports
-- Themes
2) Report (Jasper)
-- What research do we each need to do
3) Installer (Eric)
4) Documentation / Front-end
-- Manual Installations
-- How To: Make your own syntax 
-- How To: Contribute
5) Syntax Specific Discussion
-- Robust column selection (Artem)
-- Nucleotide Color Scheme
6) Assign Tasks
7) ... hack till you have to go home.

**Comment by ababaian** [comment]
I'm running late: y'all can  start without me but I'll be there at 6:30. Maybe get the guys on skype :)

**Comment by alyeffy** [comment]
Do we have a room booked? Also what are everyone's skype IDs?

**Comment by fransilvion** [comment]
I will have to leave early, at 6:40 approximately...

2017-11-01 20:04 GMT-04:00 Alyssa Fegen <notifications@github.com>:

**Comment by ababaian** [comment]
We don't have a room until 7pm but we can meet outside of it when the other group leaves:

IK Barber Learning Centre - Group Study Rooms (MAA Library) - Room 317

I'm on my way now.

**Comment by ababaian** [comment]
For remote ppl: join the discord: https://discord.gg/hA58RR

**Comment by fransilvion** [comment]
Where are you guys? I am near 300 room

четверг, 2 ноября 2017 г. пользователь Artem Babaian написал:

**Comment by ababaian** [comment]
rm 317

**Comment by alyeffy** [comment]
Meeting Minutes can be found here:
https://docs.google.com/document/d/1UzXFvXoFyR9GEnLwKR7z--yfM77R-OpqMJzbpeiYgNs/edit?usp=sharing
