### ISSUE TITLE
bioSyntax Meeting 2

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#21]
### Time / Place
Please complete the [dudle poll](https://dudle.inf.tu-dresden.de/bioSyntax2/) to select a date for the next meeting.

The next meeting will be **6:30pm on Wednesday November 15th, in Room 416 Irving Barber Library**. Note the half hour delay due to room booking. We'll discord in remote people.

###  Assignments / Items Due
[Minutes from Meeting 1](https://docs.google.com/document/d/1UzXFvXoFyR9GEnLwKR7z--yfM77R-OpqMJzbpeiYgNs/edit?usp=sharing)

- [x] Vim Core Syntaxes  - Jasper / Gherman
- [x] Gedit Core Syntaxes - Anicet / Jeff
- [x] Less syntaxes - Artem
- [ ] SAM gedit/sublime - Eric
- [x] Running Installer - Eric / Alyssa
- [x] Port to Atom - Alyssa
- [x] Outline for website documentation - Artem // Alyssa

I'll book a room in the library once we have a date; remote ppl we can Discord again.

### Agenda (add items)
0) Wrap-up-a-thon Date
1) Define Release 1.0 'Finish Criteria' for bioSyntax (All)
-- File Formats
-- Software Ports
-- Themes
2) Report (Jasper)
-- [Authorship. Requirements + Responsibilities for each us](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html)
-- Funding for publication, hackseq... others
3) Installer (Eric + Alyssa)
4) Documentation / Website (Alyssa + Artem)
-- Website drafted
-- Manual Installations
-- How To: Make your own syntax 
-- How To: Contribute
5) Syntax Specific Discussion
6) Assign Tasks

**Comment by Jwong684** [comment]
Here is the discord link:

https://discord.gg/kp85mc

**Comment by alyeffy** [comment]
[Meeting Minutes](https://docs.google.com/document/d/17ZEINNX_1YipUBIwOKG4rxBja2x8iYEXTBSxlseAcoo/edit?usp=sharing)
