### ISSUE TITLE
Team Meeting Times

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#4]
Schedule for team meetings on [Slack Channel](https://hackseq.slack.com)

For the people working remote; make sure to login for these times on Slack.

**Day 1**
- [x] Initial Meeting: 9:30AM PST
- [ ] Mid-day Meet: 1:00PM PST
- [ ] End of day Meet: 4:30PM PST

**Day 2**
- [ ] Initial Meeting: 9:30AM PST
- [ ] Mid-day Meet: 1:00PM PST
- [ ] End of day Meet: 4:30PM PST

**Day 3**
- [ ] Initial Meeting: 9:30AM PST
- [ ] Mid-day Meet: 1:00PM PST
- [ ] End of day Meet: 4:30PM PST

**Comment by Ebedthan** [comment]
ok @ababaian
