### ISSUE TITLE
Fasta Syntax

### ISSUE THREAD

**Issue by Ebedthan** [ababaian/bioSyntax#7]
Fasta files are appropriates for viewing:  
* DNA sequences;
* RNA sequences;
* and protein sequences.

I have added example files of RNA and protein sequences.

**Comment by ababaian** [comment]
> @ababaian did you check my job in the /syntax/gedit/ folder ? I think i moved forward porting syntax to gedit. Can you evaluate it, and send me an review on the works? Thanks

@Ebedthan Yes I can do this. I'll need a day or two though if that's OK.
