### ISSUE TITLE
bioSyntax Theme

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#8]
## Special Biological Classes and their target 'scope'
In the bioSyntax Theme there are custom defined colors / classes for highlighting. Entities which are 'biological' such as genomic coordinates, nucleotides, software names should look the same across all formats so we are defining one naming scheme (also called Scope) for each of these bio-classes

If you have a different type of data to add; comment below and I'll add it to our list so it's color scheme works with everything here

### As of November 30th, 2017. There is now a single unified theme defined in Hex / ANSI / Cterm for biological classes. All of the sublime syntax variable names and the bioMonokai theme have been updated to refer to the unified theme.

**Comment by ababaian** [comment]
### Todo
- Strand colors are not pretty; make it nice

**Comment by alyeffy** [comment]
Mac Path for Sublime Color Theme package installation:
/Applications/Sublime Text.app/Contents/MacOS/Packages

**Comment by ababaian** [comment]
### Scopes to add
-- Software / Commands
-- Command line string
-- Contig Type in GTF
-- Cigar String (?)
-- Gene Names
-- ...

**Comment by ababaian** [comment]
It's always kind of bothered me that there isn't a good coloring scheme for the entire IUPAC nucleotide letters, and the IGV\Jalview based scheme we're using now colors C as blue and G as orange which always drove me a little bit nuts. I spent some time with a color wheel and I think I have an alpha ready for a theme for the entire IUPAC nts which makes sense. It should also be compatible with all the different forms of color blindness.
Comments are welcome : )

![nt_iupac_v0 1](https://user-images.githubusercontent.com/9220907/32239093-d369061c-be26-11e7-876f-4c79501dfe3c.png)

The primary bases are highlighted using complementary color pairs blue-orange (T-G) and red-green (C-G), and shaded enough to be distinguishable by color-blind individuals. Strong nucleotides (G and C) are warm colors and weak nucleotides  (A and T) are cool colors to easily contrast GC-rich sequence areas from AT-rich areas. Further ambiguous nucleotides are colored by approximate mixing of the primary colors and such that opposing ambiguous nucleotide codes (puRine-pYrimidine, Weak-Strong and aMino-Keto) are complementary. Triple ambiguous nucleotides (D, H, B and V) highlights are lightened, ultimately with aNy or unknown (X) base being highlighted in white and gray respectively. Insertion/deletions ( - or .) are kept transparent.
